/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.enkrypt.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(20)
@org.apache.avro.specific.AvroGenerated
public class Bytes20 extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = -8013893959267586295L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Bytes20\",\"namespace\":\"io.enkrypt.avro\",\"size\":20}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new Bytes20 */
  public Bytes20() {
    super();
  }

  /**
   * Creates a new Bytes20 with the given bytes.
   * @param bytes The bytes to create the new Bytes20.
   */
  public Bytes20(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter<Bytes20>(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader<Bytes20>(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
