/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.enkrypt.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LogInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7701058027005603420L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogInfo\",\"namespace\":\"io.enkrypt.avro\",\"fields\":[{\"name\":\"address\",\"type\":{\"type\":\"fixed\",\"name\":\"Bytes20\",\"size\":20}},{\"name\":\"topics\",\"type\":{\"type\":\"array\",\"items\":\"bytes\"}},{\"name\":\"data\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LogInfo> ENCODER =
      new BinaryMessageEncoder<LogInfo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LogInfo> DECODER =
      new BinaryMessageDecoder<LogInfo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<LogInfo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<LogInfo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LogInfo>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this LogInfo to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a LogInfo from a ByteBuffer. */
  public static LogInfo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public io.enkrypt.avro.Bytes20 address;
  @Deprecated public java.util.List<java.nio.ByteBuffer> topics;
  @Deprecated public java.nio.ByteBuffer data;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogInfo() {}

  /**
   * All-args constructor.
   * @param address The new value for address
   * @param topics The new value for topics
   * @param data The new value for data
   */
  public LogInfo(io.enkrypt.avro.Bytes20 address, java.util.List<java.nio.ByteBuffer> topics, java.nio.ByteBuffer data) {
    this.address = address;
    this.topics = topics;
    this.data = data;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return address;
    case 1: return topics;
    case 2: return data;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: address = (io.enkrypt.avro.Bytes20)value$; break;
    case 1: topics = (java.util.List<java.nio.ByteBuffer>)value$; break;
    case 2: data = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public io.enkrypt.avro.Bytes20 getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(io.enkrypt.avro.Bytes20 value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'topics' field.
   * @return The value of the 'topics' field.
   */
  public java.util.List<java.nio.ByteBuffer> getTopics() {
    return topics;
  }

  /**
   * Sets the value of the 'topics' field.
   * @param value the value to set.
   */
  public void setTopics(java.util.List<java.nio.ByteBuffer> value) {
    this.topics = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Creates a new LogInfo RecordBuilder.
   * @return A new LogInfo RecordBuilder
   */
  public static io.enkrypt.avro.LogInfo.Builder newBuilder() {
    return new io.enkrypt.avro.LogInfo.Builder();
  }

  /**
   * Creates a new LogInfo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogInfo RecordBuilder
   */
  public static io.enkrypt.avro.LogInfo.Builder newBuilder(io.enkrypt.avro.LogInfo.Builder other) {
    return new io.enkrypt.avro.LogInfo.Builder(other);
  }

  /**
   * Creates a new LogInfo RecordBuilder by copying an existing LogInfo instance.
   * @param other The existing instance to copy.
   * @return A new LogInfo RecordBuilder
   */
  public static io.enkrypt.avro.LogInfo.Builder newBuilder(io.enkrypt.avro.LogInfo other) {
    return new io.enkrypt.avro.LogInfo.Builder(other);
  }

  /**
   * RecordBuilder for LogInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogInfo>
    implements org.apache.avro.data.RecordBuilder<LogInfo> {

    private io.enkrypt.avro.Bytes20 address;
    private java.util.List<java.nio.ByteBuffer> topics;
    private java.nio.ByteBuffer data;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.enkrypt.avro.LogInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.topics)) {
        this.topics = data().deepCopy(fields()[1].schema(), other.topics);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LogInfo instance
     * @param other The existing instance to copy.
     */
    private Builder(io.enkrypt.avro.LogInfo other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.topics)) {
        this.topics = data().deepCopy(fields()[1].schema(), other.topics);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public io.enkrypt.avro.Bytes20 getAddress() {
      return address;
    }

    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public io.enkrypt.avro.LogInfo.Builder setAddress(io.enkrypt.avro.Bytes20 value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public io.enkrypt.avro.LogInfo.Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'topics' field.
      * @return The value.
      */
    public java.util.List<java.nio.ByteBuffer> getTopics() {
      return topics;
    }

    /**
      * Sets the value of the 'topics' field.
      * @param value The value of 'topics'.
      * @return This builder.
      */
    public io.enkrypt.avro.LogInfo.Builder setTopics(java.util.List<java.nio.ByteBuffer> value) {
      validate(fields()[1], value);
      this.topics = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'topics' field has been set.
      * @return True if the 'topics' field has been set, false otherwise.
      */
    public boolean hasTopics() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'topics' field.
      * @return This builder.
      */
    public io.enkrypt.avro.LogInfo.Builder clearTopics() {
      topics = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public io.enkrypt.avro.LogInfo.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.data = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public io.enkrypt.avro.LogInfo.Builder clearData() {
      data = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LogInfo build() {
      try {
        LogInfo record = new LogInfo();
        record.address = fieldSetFlags()[0] ? this.address : (io.enkrypt.avro.Bytes20) defaultValue(fields()[0]);
        record.topics = fieldSetFlags()[1] ? this.topics : (java.util.List<java.nio.ByteBuffer>) defaultValue(fields()[1]);
        record.data = fieldSetFlags()[2] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LogInfo>
    WRITER$ = (org.apache.avro.io.DatumWriter<LogInfo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LogInfo>
    READER$ = (org.apache.avro.io.DatumReader<LogInfo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
