/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.enkrypt.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Transaction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 529150552887942992L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Transaction\",\"namespace\":\"io.enkrypt.avro\",\"fields\":[{\"name\":\"hash\",\"type\":{\"type\":\"fixed\",\"name\":\"Bytes32\",\"size\":32}},{\"name\":\"blockHash\",\"type\":[\"null\",\"Bytes32\"],\"default\":null},{\"name\":\"nonce\",\"type\":\"bytes\"},{\"name\":\"transactionIndex\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"from\",\"type\":[\"null\",{\"type\":\"fixed\",\"name\":\"Bytes20\",\"size\":20}]},{\"name\":\"to\",\"type\":[\"null\",\"Bytes20\"],\"default\":null},{\"name\":\"value\",\"type\":\"bytes\"},{\"name\":\"gasPrice\",\"type\":\"bytes\"},{\"name\":\"gasLimit\",\"type\":\"bytes\"},{\"name\":\"data\",\"type\":[\"null\",\"bytes\"],\"default\":null},{\"name\":\"receipt\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"TransactionReceipt\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"postTxState\",\"type\":\"bytes\"},{\"name\":\"cumulativeGas\",\"type\":\"bytes\"},{\"name\":\"bloomFilter\",\"type\":\"bytes\"},{\"name\":\"gasUsed\",\"type\":\"bytes\"},{\"name\":\"executionResult\",\"type\":\"bytes\"},{\"name\":\"logs\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LogInfo\",\"fields\":[{\"name\":\"address\",\"type\":\"Bytes20\"},{\"name\":\"topics\",\"type\":{\"type\":\"array\",\"items\":\"bytes\"}},{\"name\":\"data\",\"type\":\"bytes\"}]}}}]}]},{\"name\":\"v\",\"type\":\"bytes\"},{\"name\":\"r\",\"type\":\"bytes\"},{\"name\":\"s\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Transaction> ENCODER =
      new BinaryMessageEncoder<Transaction>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Transaction> DECODER =
      new BinaryMessageDecoder<Transaction>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Transaction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Transaction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Transaction>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Transaction to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Transaction from a ByteBuffer. */
  public static Transaction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public io.enkrypt.avro.Bytes32 hash;
  @Deprecated public io.enkrypt.avro.Bytes32 blockHash;
  @Deprecated public java.nio.ByteBuffer nonce;
  @Deprecated public java.lang.Integer transactionIndex;
  @Deprecated public io.enkrypt.avro.Bytes20 from;
  @Deprecated public io.enkrypt.avro.Bytes20 to;
  @Deprecated public java.nio.ByteBuffer value;
  @Deprecated public java.nio.ByteBuffer gasPrice;
  @Deprecated public java.nio.ByteBuffer gasLimit;
  @Deprecated public java.nio.ByteBuffer data;
  @Deprecated public io.enkrypt.avro.TransactionReceipt receipt;
  @Deprecated public java.nio.ByteBuffer v;
  @Deprecated public java.nio.ByteBuffer r;
  @Deprecated public java.nio.ByteBuffer s;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Transaction() {}

  /**
   * All-args constructor.
   * @param hash The new value for hash
   * @param blockHash The new value for blockHash
   * @param nonce The new value for nonce
   * @param transactionIndex The new value for transactionIndex
   * @param from The new value for from
   * @param to The new value for to
   * @param value The new value for value
   * @param gasPrice The new value for gasPrice
   * @param gasLimit The new value for gasLimit
   * @param data The new value for data
   * @param receipt The new value for receipt
   * @param v The new value for v
   * @param r The new value for r
   * @param s The new value for s
   */
  public Transaction(io.enkrypt.avro.Bytes32 hash, io.enkrypt.avro.Bytes32 blockHash, java.nio.ByteBuffer nonce, java.lang.Integer transactionIndex, io.enkrypt.avro.Bytes20 from, io.enkrypt.avro.Bytes20 to, java.nio.ByteBuffer value, java.nio.ByteBuffer gasPrice, java.nio.ByteBuffer gasLimit, java.nio.ByteBuffer data, io.enkrypt.avro.TransactionReceipt receipt, java.nio.ByteBuffer v, java.nio.ByteBuffer r, java.nio.ByteBuffer s) {
    this.hash = hash;
    this.blockHash = blockHash;
    this.nonce = nonce;
    this.transactionIndex = transactionIndex;
    this.from = from;
    this.to = to;
    this.value = value;
    this.gasPrice = gasPrice;
    this.gasLimit = gasLimit;
    this.data = data;
    this.receipt = receipt;
    this.v = v;
    this.r = r;
    this.s = s;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return hash;
    case 1: return blockHash;
    case 2: return nonce;
    case 3: return transactionIndex;
    case 4: return from;
    case 5: return to;
    case 6: return value;
    case 7: return gasPrice;
    case 8: return gasLimit;
    case 9: return data;
    case 10: return receipt;
    case 11: return v;
    case 12: return r;
    case 13: return s;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: hash = (io.enkrypt.avro.Bytes32)value$; break;
    case 1: blockHash = (io.enkrypt.avro.Bytes32)value$; break;
    case 2: nonce = (java.nio.ByteBuffer)value$; break;
    case 3: transactionIndex = (java.lang.Integer)value$; break;
    case 4: from = (io.enkrypt.avro.Bytes20)value$; break;
    case 5: to = (io.enkrypt.avro.Bytes20)value$; break;
    case 6: value = (java.nio.ByteBuffer)value$; break;
    case 7: gasPrice = (java.nio.ByteBuffer)value$; break;
    case 8: gasLimit = (java.nio.ByteBuffer)value$; break;
    case 9: data = (java.nio.ByteBuffer)value$; break;
    case 10: receipt = (io.enkrypt.avro.TransactionReceipt)value$; break;
    case 11: v = (java.nio.ByteBuffer)value$; break;
    case 12: r = (java.nio.ByteBuffer)value$; break;
    case 13: s = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'hash' field.
   * @return The value of the 'hash' field.
   */
  public io.enkrypt.avro.Bytes32 getHash() {
    return hash;
  }

  /**
   * Sets the value of the 'hash' field.
   * @param value the value to set.
   */
  public void setHash(io.enkrypt.avro.Bytes32 value) {
    this.hash = value;
  }

  /**
   * Gets the value of the 'blockHash' field.
   * @return The value of the 'blockHash' field.
   */
  public io.enkrypt.avro.Bytes32 getBlockHash() {
    return blockHash;
  }

  /**
   * Sets the value of the 'blockHash' field.
   * @param value the value to set.
   */
  public void setBlockHash(io.enkrypt.avro.Bytes32 value) {
    this.blockHash = value;
  }

  /**
   * Gets the value of the 'nonce' field.
   * @return The value of the 'nonce' field.
   */
  public java.nio.ByteBuffer getNonce() {
    return nonce;
  }

  /**
   * Sets the value of the 'nonce' field.
   * @param value the value to set.
   */
  public void setNonce(java.nio.ByteBuffer value) {
    this.nonce = value;
  }

  /**
   * Gets the value of the 'transactionIndex' field.
   * @return The value of the 'transactionIndex' field.
   */
  public java.lang.Integer getTransactionIndex() {
    return transactionIndex;
  }

  /**
   * Sets the value of the 'transactionIndex' field.
   * @param value the value to set.
   */
  public void setTransactionIndex(java.lang.Integer value) {
    this.transactionIndex = value;
  }

  /**
   * Gets the value of the 'from' field.
   * @return The value of the 'from' field.
   */
  public io.enkrypt.avro.Bytes20 getFrom() {
    return from;
  }

  /**
   * Sets the value of the 'from' field.
   * @param value the value to set.
   */
  public void setFrom(io.enkrypt.avro.Bytes20 value) {
    this.from = value;
  }

  /**
   * Gets the value of the 'to' field.
   * @return The value of the 'to' field.
   */
  public io.enkrypt.avro.Bytes20 getTo() {
    return to;
  }

  /**
   * Sets the value of the 'to' field.
   * @param value the value to set.
   */
  public void setTo(io.enkrypt.avro.Bytes20 value) {
    this.to = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.nio.ByteBuffer getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.nio.ByteBuffer value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'gasPrice' field.
   * @return The value of the 'gasPrice' field.
   */
  public java.nio.ByteBuffer getGasPrice() {
    return gasPrice;
  }

  /**
   * Sets the value of the 'gasPrice' field.
   * @param value the value to set.
   */
  public void setGasPrice(java.nio.ByteBuffer value) {
    this.gasPrice = value;
  }

  /**
   * Gets the value of the 'gasLimit' field.
   * @return The value of the 'gasLimit' field.
   */
  public java.nio.ByteBuffer getGasLimit() {
    return gasLimit;
  }

  /**
   * Sets the value of the 'gasLimit' field.
   * @param value the value to set.
   */
  public void setGasLimit(java.nio.ByteBuffer value) {
    this.gasLimit = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'receipt' field.
   * @return The value of the 'receipt' field.
   */
  public io.enkrypt.avro.TransactionReceipt getReceipt() {
    return receipt;
  }

  /**
   * Sets the value of the 'receipt' field.
   * @param value the value to set.
   */
  public void setReceipt(io.enkrypt.avro.TransactionReceipt value) {
    this.receipt = value;
  }

  /**
   * Gets the value of the 'v' field.
   * @return The value of the 'v' field.
   */
  public java.nio.ByteBuffer getV() {
    return v;
  }

  /**
   * Sets the value of the 'v' field.
   * @param value the value to set.
   */
  public void setV(java.nio.ByteBuffer value) {
    this.v = value;
  }

  /**
   * Gets the value of the 'r' field.
   * @return The value of the 'r' field.
   */
  public java.nio.ByteBuffer getR() {
    return r;
  }

  /**
   * Sets the value of the 'r' field.
   * @param value the value to set.
   */
  public void setR(java.nio.ByteBuffer value) {
    this.r = value;
  }

  /**
   * Gets the value of the 's' field.
   * @return The value of the 's' field.
   */
  public java.nio.ByteBuffer getS() {
    return s;
  }

  /**
   * Sets the value of the 's' field.
   * @param value the value to set.
   */
  public void setS(java.nio.ByteBuffer value) {
    this.s = value;
  }

  /**
   * Creates a new Transaction RecordBuilder.
   * @return A new Transaction RecordBuilder
   */
  public static io.enkrypt.avro.Transaction.Builder newBuilder() {
    return new io.enkrypt.avro.Transaction.Builder();
  }

  /**
   * Creates a new Transaction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Transaction RecordBuilder
   */
  public static io.enkrypt.avro.Transaction.Builder newBuilder(io.enkrypt.avro.Transaction.Builder other) {
    return new io.enkrypt.avro.Transaction.Builder(other);
  }

  /**
   * Creates a new Transaction RecordBuilder by copying an existing Transaction instance.
   * @param other The existing instance to copy.
   * @return A new Transaction RecordBuilder
   */
  public static io.enkrypt.avro.Transaction.Builder newBuilder(io.enkrypt.avro.Transaction other) {
    return new io.enkrypt.avro.Transaction.Builder(other);
  }

  /**
   * RecordBuilder for Transaction instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Transaction>
    implements org.apache.avro.data.RecordBuilder<Transaction> {

    private io.enkrypt.avro.Bytes32 hash;
    private io.enkrypt.avro.Bytes32 blockHash;
    private java.nio.ByteBuffer nonce;
    private java.lang.Integer transactionIndex;
    private io.enkrypt.avro.Bytes20 from;
    private io.enkrypt.avro.Bytes20 to;
    private java.nio.ByteBuffer value;
    private java.nio.ByteBuffer gasPrice;
    private java.nio.ByteBuffer gasLimit;
    private java.nio.ByteBuffer data;
    private io.enkrypt.avro.TransactionReceipt receipt;
    private io.enkrypt.avro.TransactionReceipt.Builder receiptBuilder;
    private java.nio.ByteBuffer v;
    private java.nio.ByteBuffer r;
    private java.nio.ByteBuffer s;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.enkrypt.avro.Transaction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.hash)) {
        this.hash = data().deepCopy(fields()[0].schema(), other.hash);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.blockHash)) {
        this.blockHash = data().deepCopy(fields()[1].schema(), other.blockHash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nonce)) {
        this.nonce = data().deepCopy(fields()[2].schema(), other.nonce);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.transactionIndex)) {
        this.transactionIndex = data().deepCopy(fields()[3].schema(), other.transactionIndex);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.from)) {
        this.from = data().deepCopy(fields()[4].schema(), other.from);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.to)) {
        this.to = data().deepCopy(fields()[5].schema(), other.to);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.value)) {
        this.value = data().deepCopy(fields()[6].schema(), other.value);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.gasPrice)) {
        this.gasPrice = data().deepCopy(fields()[7].schema(), other.gasPrice);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.gasLimit)) {
        this.gasLimit = data().deepCopy(fields()[8].schema(), other.gasLimit);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.data)) {
        this.data = data().deepCopy(fields()[9].schema(), other.data);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.receipt)) {
        this.receipt = data().deepCopy(fields()[10].schema(), other.receipt);
        fieldSetFlags()[10] = true;
      }
      if (other.hasReceiptBuilder()) {
        this.receiptBuilder = io.enkrypt.avro.TransactionReceipt.newBuilder(other.getReceiptBuilder());
      }
      if (isValidValue(fields()[11], other.v)) {
        this.v = data().deepCopy(fields()[11].schema(), other.v);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.r)) {
        this.r = data().deepCopy(fields()[12].schema(), other.r);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.s)) {
        this.s = data().deepCopy(fields()[13].schema(), other.s);
        fieldSetFlags()[13] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Transaction instance
     * @param other The existing instance to copy.
     */
    private Builder(io.enkrypt.avro.Transaction other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.hash)) {
        this.hash = data().deepCopy(fields()[0].schema(), other.hash);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.blockHash)) {
        this.blockHash = data().deepCopy(fields()[1].schema(), other.blockHash);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.nonce)) {
        this.nonce = data().deepCopy(fields()[2].schema(), other.nonce);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.transactionIndex)) {
        this.transactionIndex = data().deepCopy(fields()[3].schema(), other.transactionIndex);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.from)) {
        this.from = data().deepCopy(fields()[4].schema(), other.from);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.to)) {
        this.to = data().deepCopy(fields()[5].schema(), other.to);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.value)) {
        this.value = data().deepCopy(fields()[6].schema(), other.value);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.gasPrice)) {
        this.gasPrice = data().deepCopy(fields()[7].schema(), other.gasPrice);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.gasLimit)) {
        this.gasLimit = data().deepCopy(fields()[8].schema(), other.gasLimit);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.data)) {
        this.data = data().deepCopy(fields()[9].schema(), other.data);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.receipt)) {
        this.receipt = data().deepCopy(fields()[10].schema(), other.receipt);
        fieldSetFlags()[10] = true;
      }
      this.receiptBuilder = null;
      if (isValidValue(fields()[11], other.v)) {
        this.v = data().deepCopy(fields()[11].schema(), other.v);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.r)) {
        this.r = data().deepCopy(fields()[12].schema(), other.r);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.s)) {
        this.s = data().deepCopy(fields()[13].schema(), other.s);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'hash' field.
      * @return The value.
      */
    public io.enkrypt.avro.Bytes32 getHash() {
      return hash;
    }

    /**
      * Sets the value of the 'hash' field.
      * @param value The value of 'hash'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setHash(io.enkrypt.avro.Bytes32 value) {
      validate(fields()[0], value);
      this.hash = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'hash' field has been set.
      * @return True if the 'hash' field has been set, false otherwise.
      */
    public boolean hasHash() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'hash' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearHash() {
      hash = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'blockHash' field.
      * @return The value.
      */
    public io.enkrypt.avro.Bytes32 getBlockHash() {
      return blockHash;
    }

    /**
      * Sets the value of the 'blockHash' field.
      * @param value The value of 'blockHash'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setBlockHash(io.enkrypt.avro.Bytes32 value) {
      validate(fields()[1], value);
      this.blockHash = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'blockHash' field has been set.
      * @return True if the 'blockHash' field has been set, false otherwise.
      */
    public boolean hasBlockHash() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'blockHash' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearBlockHash() {
      blockHash = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'nonce' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getNonce() {
      return nonce;
    }

    /**
      * Sets the value of the 'nonce' field.
      * @param value The value of 'nonce'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setNonce(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.nonce = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'nonce' field has been set.
      * @return True if the 'nonce' field has been set, false otherwise.
      */
    public boolean hasNonce() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'nonce' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearNonce() {
      nonce = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionIndex' field.
      * @return The value.
      */
    public java.lang.Integer getTransactionIndex() {
      return transactionIndex;
    }

    /**
      * Sets the value of the 'transactionIndex' field.
      * @param value The value of 'transactionIndex'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setTransactionIndex(java.lang.Integer value) {
      validate(fields()[3], value);
      this.transactionIndex = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionIndex' field has been set.
      * @return True if the 'transactionIndex' field has been set, false otherwise.
      */
    public boolean hasTransactionIndex() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'transactionIndex' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearTransactionIndex() {
      transactionIndex = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'from' field.
      * @return The value.
      */
    public io.enkrypt.avro.Bytes20 getFrom() {
      return from;
    }

    /**
      * Sets the value of the 'from' field.
      * @param value The value of 'from'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setFrom(io.enkrypt.avro.Bytes20 value) {
      validate(fields()[4], value);
      this.from = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'from' field has been set.
      * @return True if the 'from' field has been set, false otherwise.
      */
    public boolean hasFrom() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'from' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearFrom() {
      from = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'to' field.
      * @return The value.
      */
    public io.enkrypt.avro.Bytes20 getTo() {
      return to;
    }

    /**
      * Sets the value of the 'to' field.
      * @param value The value of 'to'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setTo(io.enkrypt.avro.Bytes20 value) {
      validate(fields()[5], value);
      this.to = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'to' field has been set.
      * @return True if the 'to' field has been set, false otherwise.
      */
    public boolean hasTo() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'to' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearTo() {
      to = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setValue(java.nio.ByteBuffer value) {
      validate(fields()[6], value);
      this.value = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearValue() {
      value = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'gasPrice' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getGasPrice() {
      return gasPrice;
    }

    /**
      * Sets the value of the 'gasPrice' field.
      * @param value The value of 'gasPrice'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setGasPrice(java.nio.ByteBuffer value) {
      validate(fields()[7], value);
      this.gasPrice = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'gasPrice' field has been set.
      * @return True if the 'gasPrice' field has been set, false otherwise.
      */
    public boolean hasGasPrice() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'gasPrice' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearGasPrice() {
      gasPrice = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'gasLimit' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getGasLimit() {
      return gasLimit;
    }

    /**
      * Sets the value of the 'gasLimit' field.
      * @param value The value of 'gasLimit'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setGasLimit(java.nio.ByteBuffer value) {
      validate(fields()[8], value);
      this.gasLimit = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'gasLimit' field has been set.
      * @return True if the 'gasLimit' field has been set, false otherwise.
      */
    public boolean hasGasLimit() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'gasLimit' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearGasLimit() {
      gasLimit = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[9], value);
      this.data = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearData() {
      data = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'receipt' field.
      * @return The value.
      */
    public io.enkrypt.avro.TransactionReceipt getReceipt() {
      return receipt;
    }

    /**
      * Sets the value of the 'receipt' field.
      * @param value The value of 'receipt'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setReceipt(io.enkrypt.avro.TransactionReceipt value) {
      validate(fields()[10], value);
      this.receiptBuilder = null;
      this.receipt = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'receipt' field has been set.
      * @return True if the 'receipt' field has been set, false otherwise.
      */
    public boolean hasReceipt() {
      return fieldSetFlags()[10];
    }

    /**
     * Gets the Builder instance for the 'receipt' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.enkrypt.avro.TransactionReceipt.Builder getReceiptBuilder() {
      if (receiptBuilder == null) {
        if (hasReceipt()) {
          setReceiptBuilder(io.enkrypt.avro.TransactionReceipt.newBuilder(receipt));
        } else {
          setReceiptBuilder(io.enkrypt.avro.TransactionReceipt.newBuilder());
        }
      }
      return receiptBuilder;
    }

    /**
     * Sets the Builder instance for the 'receipt' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.enkrypt.avro.Transaction.Builder setReceiptBuilder(io.enkrypt.avro.TransactionReceipt.Builder value) {
      clearReceipt();
      receiptBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'receipt' field has an active Builder instance
     * @return True if the 'receipt' field has an active Builder instance
     */
    public boolean hasReceiptBuilder() {
      return receiptBuilder != null;
    }

    /**
      * Clears the value of the 'receipt' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearReceipt() {
      receipt = null;
      receiptBuilder = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'v' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getV() {
      return v;
    }

    /**
      * Sets the value of the 'v' field.
      * @param value The value of 'v'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setV(java.nio.ByteBuffer value) {
      validate(fields()[11], value);
      this.v = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'v' field has been set.
      * @return True if the 'v' field has been set, false otherwise.
      */
    public boolean hasV() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'v' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearV() {
      v = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'r' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getR() {
      return r;
    }

    /**
      * Sets the value of the 'r' field.
      * @param value The value of 'r'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setR(java.nio.ByteBuffer value) {
      validate(fields()[12], value);
      this.r = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'r' field has been set.
      * @return True if the 'r' field has been set, false otherwise.
      */
    public boolean hasR() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'r' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearR() {
      r = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 's' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getS() {
      return s;
    }

    /**
      * Sets the value of the 's' field.
      * @param value The value of 's'.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder setS(java.nio.ByteBuffer value) {
      validate(fields()[13], value);
      this.s = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 's' field has been set.
      * @return True if the 's' field has been set, false otherwise.
      */
    public boolean hasS() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 's' field.
      * @return This builder.
      */
    public io.enkrypt.avro.Transaction.Builder clearS() {
      s = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Transaction build() {
      try {
        Transaction record = new Transaction();
        record.hash = fieldSetFlags()[0] ? this.hash : (io.enkrypt.avro.Bytes32) defaultValue(fields()[0]);
        record.blockHash = fieldSetFlags()[1] ? this.blockHash : (io.enkrypt.avro.Bytes32) defaultValue(fields()[1]);
        record.nonce = fieldSetFlags()[2] ? this.nonce : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        record.transactionIndex = fieldSetFlags()[3] ? this.transactionIndex : (java.lang.Integer) defaultValue(fields()[3]);
        record.from = fieldSetFlags()[4] ? this.from : (io.enkrypt.avro.Bytes20) defaultValue(fields()[4]);
        record.to = fieldSetFlags()[5] ? this.to : (io.enkrypt.avro.Bytes20) defaultValue(fields()[5]);
        record.value = fieldSetFlags()[6] ? this.value : (java.nio.ByteBuffer) defaultValue(fields()[6]);
        record.gasPrice = fieldSetFlags()[7] ? this.gasPrice : (java.nio.ByteBuffer) defaultValue(fields()[7]);
        record.gasLimit = fieldSetFlags()[8] ? this.gasLimit : (java.nio.ByteBuffer) defaultValue(fields()[8]);
        record.data = fieldSetFlags()[9] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[9]);
        if (receiptBuilder != null) {
          record.receipt = this.receiptBuilder.build();
        } else {
          record.receipt = fieldSetFlags()[10] ? this.receipt : (io.enkrypt.avro.TransactionReceipt) defaultValue(fields()[10]);
        }
        record.v = fieldSetFlags()[11] ? this.v : (java.nio.ByteBuffer) defaultValue(fields()[11]);
        record.r = fieldSetFlags()[12] ? this.r : (java.nio.ByteBuffer) defaultValue(fields()[12]);
        record.s = fieldSetFlags()[13] ? this.s : (java.nio.ByteBuffer) defaultValue(fields()[13]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Transaction>
    WRITER$ = (org.apache.avro.io.DatumWriter<Transaction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Transaction>
    READER$ = (org.apache.avro.io.DatumReader<Transaction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
